#!/bin/bash
echo '                       __    
  ____ _____ ___  ____/ /____
 / __ `/ __ `__ \/ __  / ___/
/ /_/ / / / / / / /_/ (__  ) 
\__, /_/ /_/ /_/\__,_/____/  
  /_/                        
'
for (( ; ; ))
do
   read -p "> " file
   file2=$(echo $file | tr -d "'")
   file1=$(echo $file2 | tr -d '"')
   echo "$file1"
   if [[ "$OSTYPE" == "darwin"* ]]; then
        shasum -a 256 "$file1"
        md5 "$file1"
   else
        sha256sum "$file1"
        md5sum "$file1"
   fi

   
done
